<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Products On White PhotographyChicago United StatesStarting price200 USDJobs completed10Rating50(10)</name>
   <tag></tag>
   <elementGuidId>5b59e8dc-0883-4787-9068-bddd783bc8da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-experts-mount']/div/div/div/main/div/div[2]/div/section[2]/div[2]/div[2]/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3iz-t</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products On White PhotographyChicago, United StatesStarting price$200 USDJobs completed10Rating5.0(10)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-experts-mount&quot;)/div[1]/div[@class=&quot;_2BPnT&quot;]/div[@class=&quot;_3o2C5&quot;]/main[@class=&quot;_3EE3N&quot;]/div[@class=&quot;Zk7Cl&quot;]/div[@class=&quot;_1_tev&quot;]/div[@class=&quot;_2fA-Y&quot;]/section[@class=&quot;jGIW4&quot;]/div[2]/div[@class=&quot;kVWrj&quot;]/a[1]/div[@class=&quot;Polaris-Card&quot;]/div[@class=&quot;_3iz-t&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-experts-mount']/div/div/div/main/div/div[2]/div/section[2]/div[2]/div[2]/a/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(12)'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div</value>
   </webElementXpaths>
</WebElementEntity>
