<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_pais</name>
   <tag></tag>
   <elementGuidId>c36335d7-2325-4beb-82e9-1dbc353834e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_1jkIv']/div[2]/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country/RegionSelect a country/regionArgentinaAustraliaBangladeshBelgiumBrazilBulgariaCanadaChinaColombiaCyprusDenmarkDominican RepublicEgyptEstoniaFinlandFranceGermanyHong KongHungaryIcelandIndiaIndonesiaIrelandIsraelItalyJapanLebanonLithuaniaMalaysiaMexicoNepalNetherlandsNew ZealandNigeriaPakistanPhilippinesPortugalRomaniaRussiaSingaporeSouth AfricaSpainSwedenSwitzerlandThailandTurkeyUkraineUnited Arab EmiratesUnited KingdomUnited StatesVietnamSelect a country/region</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_1jkIv&quot;)/div[@class=&quot;_199KU&quot;]/div[@class=&quot;Polaris-Stack Polaris-Stack--vertical&quot;]/div[@class=&quot;Polaris-Stack__Item&quot;]/div[@class=&quot;Polaris-Stack Polaris-Stack--vertical Polaris-Stack--spacingLoose&quot;]/div[@class=&quot;Polaris-Stack__Item&quot;]/div[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_1jkIv']/div[2]/div/div[2]/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum price'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum price'])[1]/following::div[20]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
