<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectPaises</name>
   <tag></tag>
   <elementGuidId>1497e97d-348f-48b4-8ab0-170f1fba9b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Select a country/regionArgentinaAustraliaBangladeshBelgiumBrazilBulgariaCanadaChinaColombiaCyprusDenmarkDominican RepublicEgyptEstoniaFinlandFranceGermanyHong KongHungaryIcelandIndiaIndonesiaIrelandIsraelItalyJapanLebanonLithuaniaMalaysiaMexicoNepalNetherlandsNew ZealandNigeriaPakistanPhilippinesPortugalRomaniaRussiaSingaporeSouth AfricaSpainSwedenSwitzerlandThailandTurkeyUkraineUnited Arab EmiratesUnited KingdomUnited StatesVietnam' or . = 'Select a country/regionArgentinaAustraliaBangladeshBelgiumBrazilBulgariaCanadaChinaColombiaCyprusDenmarkDominican RepublicEgyptEstoniaFinlandFranceGermanyHong KongHungaryIcelandIndiaIndonesiaIrelandIsraelItalyJapanLebanonLithuaniaMalaysiaMexicoNepalNetherlandsNew ZealandNigeriaPakistanPhilippinesPortugalRomaniaRussiaSingaporeSouth AfricaSpainSwedenSwitzerlandThailandTurkeyUkraineUnited Arab EmiratesUnited KingdomUnited StatesVietnam')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Select5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Select5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-Select__Input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a country/regionArgentinaAustraliaBangladeshBelgiumBrazilBulgariaCanadaChinaColombiaCyprusDenmarkDominican RepublicEgyptEstoniaFinlandFranceGermanyHong KongHungaryIcelandIndiaIndonesiaIrelandIsraelItalyJapanLebanonLithuaniaMalaysiaMexicoNepalNetherlandsNew ZealandNigeriaPakistanPhilippinesPortugalRomaniaRussiaSingaporeSouth AfricaSpainSwedenSwitzerlandThailandTurkeyUkraineUnited Arab EmiratesUnited KingdomUnited StatesVietnam</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select5&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Select5']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_1jkIv']/div[2]/div/div[2]/div/div[2]/div/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country/Region'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum price'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a country/region'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages spoken'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
